[tool.poetry]
name = "npvcc2016"
version = "1.0.4"
description = "npvcc2016: Python loader of npVCC2016 speech corpus"
authors = ["Tarepan"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tarepan/npVCC2016"


[tool.poetry.dependencies]
python = "^3.6.1"
torch = "^1.6.0"
torchaudio = "^0.6.0"
pytorch-lightning = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
